.github/workflows/anchore.yml
.grype.yaml
Dockerfile
pom.xml

**Description**
The purpose of this PR is to solve the vulnerabilities(CVE) with status high
**List of changes**
- Docker file
- Anchore
- Update dependencies
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

feat: IDP-1500-risoluzione-cve-idpay-recovery-error-topic

---

.devops/deploy-pipelines.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
.releaserc.json
Dockerfile
helm/Chart.yaml
helm/values.yaml

- upgrade helmchart to 2.8.0
- update anchore action triggers (on push and workflow_dispatch)
- add proper .releaserc.json + bump to semantic-release v4
- add pull request template
- fix anchor skip steps

chore: [IDP-1708] Devops fixes

---

helm/Chart.lock

chore: [IPD-1708] Devops fixes

---

.github/CODEOWNERS
CODEOWNERS

chore: update codeowners (#46)

---

.github/workflows/anchore.yml

chore: fix anchore skip step (#49)

---

Dockerfile

fix: IDP-1760 fix new critical CVE-2022-48174 (#52)

---

pom.xml

chore: Bump POM version (#55)

---

helm/values.yaml
pom.xml

fix: fix idpay-commands jaas-config

---

helm/values.yaml
pom.xml

fix: fix idpay-commands jaas-config (#58)

---

.grype.yaml
Dockerfile
pom.xml
src/main/resources/application.yml

fix: Idp 2016 fix CVE

---

.grype.yaml
Dockerfile
pom.xml
src/main/resources/application.yml

* fix CVE-2023-45853,CVE-2023-44487 in progress
* added StreamHealthIndicator
* fixed health checks indicators
* fix CVE-2023-45853,CVE-2023-44487

fix: Idp 2016 fix CVE (#60)

---

.grype.yaml
Dockerfile
helm/values.yaml
pom.xml
src/main/resources/application.yml

IDP-2003 fix mongo retry when anonymous repo
IDP-2016 fix CVE-2023-45853,CVE-2023-44487

fix: Release uat

---

Dockerfile

chore: IDP-2115 fix CVE-2023-44487 on application-insight (#63)

---

src/main/java/it/gov/pagopa/common/config/HealthIndicatorLogger.java
src/main/java/it/gov/pagopa/idpay/error_recovery/IdPayErrorRecoveryApplication.java
src/test/java/it/gov/pagopa/common/config/HealthIndicatorLoggerTest.java
src/test/java/it/gov/pagopa/common/utils/MemoryAppender.java

Add HealthIndicatorLogger
IDP 1125

fix: [IDP-1125] Log actuator health

---

src/main/java/it/gov/pagopa/idpay/error_recovery/service/ErrorMessagePublisherServiceImpl.java

fix: Fix kafka header serialization

---

pom.xml
src/main/java/it/gov/pagopa/common/config/HealthIndicatorLogger.java
src/main/java/it/gov/pagopa/idpay/error_recovery/IdPayErrorRecoveryApplication.java
src/main/java/it/gov/pagopa/idpay/error_recovery/service/ErrorMessagePublisherServiceImpl.java
src/test/java/it/gov/pagopa/common/config/HealthIndicatorLoggerTest.java
src/test/java/it/gov/pagopa/common/utils/MemoryAppender.java

Promotion to UAT
- Log actuator health -> [PR](https://github.com/pagopa/idpay-recovery-error-topic/pull/68)

feat: Promote to UAT

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/idpay/error_recovery/producer/factory/JmsPublisherFactoryServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/idpay/error_recovery/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/idpay/error_recovery/consumer/ErrorMessagesListenerTest.java

fix: IDP-2196 fix Cve

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/idpay/error_recovery/producer/factory/JmsPublisherFactoryServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/idpay/error_recovery/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/idpay/error_recovery/consumer/ErrorMessagesListenerTest.java

* fix: IDP-2196 fix Cve
* setting idle-timeout
fix: IDP-2196 fix Cve

fix: IDP-2196 fix Cve (#75)

---

.github/CODEOWNERS

chore: codeowner fix

---

specs/asyncapi.yml

[IDP-2486](https://pagopa.atlassian.net/browse/IDP-2486)
[IDP-2486]: https://pagopa.atlassian.net/browse/IDP-2486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [IDP-2486] Async documentation

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD

chore: fix-cve

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
[PR](https://github.com/pagopa/idpay-recovery-error-topic/pull/87)

chore: promote to UAT

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml
specs/asyncapi.yml

- Fix CVE [PR](https://github.com/pagopa/idpay-recovery-error-topic/pull/88)

chore: promote to MAIN
